# Simple workflow for deploying static content to GitHub Pages
name: Deploy Excel sheet

on:
  # Runs on pushes targeting the master, develop branch
  push:
    # branches: [ master, develop ]
  # Runs on pull-request targeting the master, develop branch
  pull_request:
    branches: [ master, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python -
          poetry install --only=main
      - name: Make Excel sheet
        run: |
          mkdir build
          poetry run python -m gobo excel build/GoGo房総.xlsx
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          # Upload Excel sheet
          name: excel-sheet
          path: build/GoGo房総.xlsx
